spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/hse_sc
    username: postgres-user
    password: postgres-password
    driver-class-name: org.postgresql.Driver

  cloud:
    openfeign:
      client:
        config:
          cat-facts:
            url: https://cat-fact.herokuapp.com
          omdbClient:
            url: http://www.omdbapi.com
          obsidianNotes:
            url: https://127.0.0.1:27124
            logger-level: full

#-----uncomment before running
#omdb:
#  api:
#    api-key: <here you must use your token for OMDb api>

#obsidian:
#  api:
#    token: <here you must use your token for obsidian local rest api>

logging:
  level:
    org.hse.template: debug